FROM ghcr.io/micash545/dev-containers:base-debian

ENV DEBIAN_FRONTEND=noninteractive \
    RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:/root/.local/bin:$PATH

RUN apt-get update && apt-get upgrade -y && \
   apt-get install -y build-essential gcc clang pkg-config libssl-dev && \
   apt-get clean && \
   rm -rf /var/lib/{apt,dpkg,cache,log,lists/*}/
