FROM ghcr.io/micash545/dev-containers:base-debian

ENV DEBIAN_FRONTEND=noninteractive

ARG GOLANG_VERSION=1.21.5

RUN wget https://go.dev/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz &&\
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go${GOLANG_VERSION}.linux-amd64.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/local/bin/go && \
    rm go${GOLANG_VERSION}.linux-amd64.tar.gz
