FROM ghcr.io/micash545/dev-containers:base-debian

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && \
   apt-get install -y python3 python3-pip pipx python3-poetry && \
   apt-get clean && \
   rm -rf /var/lib/{apt,dpkg,cache,log,lists/*}/
