FROM ghcr.io/micash545/dev-containers:base-ubuntu

ENV DEBIAN_FRONTEND=noninteractive

ADD nodejs/n .

RUN /bin/bash ./n lts && \
   rm n && \
   npm i -g npm yarn pnpm && \
   yarn config set enableTelemetry 0 && \
   npm cache clean
