FROM ghcr.io/micash545/dev-containers:base-debian

ENV DEBIAN_FRONTEND=noninteractive

ADD nodejs/n .

RUN /bin/bash ./n lts && \
   rm n && \
   npm i --cache /tmp/npm-cache -g npm yarn pnpm && \
   yarn config set enableTelemetry 0
