FROM docker.io/library/debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && \
   apt-get install -y curl wget make sudo openssl ca-certificates gnupg git p7zip jq && \
   apt-get clean && \
   rm -rf /var/lib/{apt,dpkg,cache,log,lists}/
