FROM docker.io/library/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && \
   apt-get install -y curl wget make sudo openssl ca-certificates gnupg && \
   apt-get clean && \
   rm -rf /var/lib/{apt,dpkg,cache,log,lists/*}/
