name: Build Python Dev Containers

on:
  push:
    paths:
    - 'python/**'
  workflow_run:
    workflows: ["Build Base Dev Container"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Python
          - dockerfile: ./python/Dockerfile.debian
            image: ghcr.io/micash545/dev-containers:python
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      
      - 
        name: Put current date into a variable
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image }} ${{ matrix.image }}-${{ steps.date.outputs.date }}
