name: Build Rust Dev Containers

on:
  push:
    paths:
    - 'rust/**'
  workflow_run:
    workflows: ["Build Base Dev Container"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Rust
          - dockerfile: ./rust/Dockerfile.debian
            image: ghcr.io/micash545/dev-containers:rust
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      
      - 
        name: Put current date into a variable
        run: |
          $NOW=& Get-Date -format yyyy-MM-dd
          echo "NOW=$NOW" >> $env:GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image }} ${{ matrix.image }}-${{env.NOW}}
